apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
      - env:
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              key: DATABASE_HOST
              name: database-env
        - name: FACEBOOK_APP_ID
          valueFrom:
            configMapKeyRef:
              key: FACEBOOK_APP_ID
              name: database-env
        - name: FACEBOOK_APP_SECRET
          valueFrom:
            configMapKeyRef:
              key: FACEBOOK_APP_SECRET
              name: database-env
        - name: KILLBOARD_URL
          valueFrom:
            configMapKeyRef:
              key: KILLBOARD_URL
              name: database-env
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: database-env
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: database-env
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: database-env
        - name: RAILS_LOG_TO_STDOUT
          valueFrom:
            configMapKeyRef:
              key: RAILS_LOG_TO_STDOUT
              name: database-env
        - name: RAILS_SERVE_STATIC_FILES
          valueFrom:
            configMapKeyRef:
              key: RAILS_SERVE_STATIC_FILES
              name: database-env
        - name: RECAPTCHA_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: RECAPTCHA_SECRET_KEY
              name: database-env
        - name: RECAPTCHA_SITE_KEY
          valueFrom:
            configMapKeyRef:
              key: RECAPTCHA_SITE_KEY
              name: database-env
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              key: REDIS_URL
              name: database-env
        - name: SECRET_KEY_BASE
          valueFrom:
            configMapKeyRef:
              key: SECRET_KEY_BASE
              name: database-env
        - name: SENDGRID_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: SENDGRID_PASSWORD
              name: database-env
        - name: SENDGRID_USERNAME
          valueFrom:
            configMapKeyRef:
              key: SENDGRID_USERNAME
              name: database-env
        image: postgres:11.2-alpine
        name: database
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      restartPolicy: Always
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data
status: {}
