apiVersion: v1
kind: Service
metadata:
  labels:
    name: database
  name: database
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    name: database
status:
  loadBalancer: {}