apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: redis
  name: redis
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - image: redis:5.0.3-alpine
        name: redis
        resources: {}
        ports:
          - containerPort: 6379
      restartPolicy: Always
status: {}
